### ISSUE TITLE
Add CLI tool to export all models to FBX with default params

### ISSUE THREAD

**Issue by amelkikh** [mikeoverbay/TankExporter#14]
Hi! 
Suggestion in subject.
Thanks a lot!

**Comment by mikeoverbay** [comment]
All 647 or what ever the count is now? with textures?

**Comment by amelkikh** [comment]
Yes, exactly.
My purpose is to convert all of them to a different format of models.

Another way to reach my goal is to upgrade FBX exporter up to 7000+ to load using three.js library
This way would be preferable.

**Comment by mikeoverbay** [comment]
I cant find a wrapper that isn't mess to sort out.
I'll work on the code tomorrow or late tonight.
I could write the tanks in a custom format for you. Just give me the format and I'll code it.

**Comment by mikeoverbay** [comment]
Tank Exporter started out as a tool to export the tanks in a simple binary triangulated format.
It was for Terra.. A WoT map viewing app.

**Comment by amelkikh** [comment]
I'm writting software to view models in a web browser WebGL. Something like 3d WoT wiki.
Your tool is great in my opinion.

**Comment by mikeoverbay** [comment]
I checked.. All the code is still there for exporting the tank as a binary blob.
I'll add in the matrices if you want or I can pre-translate the vertices. If they are pre-translated, it will make it hard to do turret rotation and gun tilt.

**Comment by mikeoverbay** [comment]
I uploaded a version that will export every tank as an FBX.
Menu -> Dump All Tanks as Binary Files.
The name is wrong because it is too much work to track the textures.
Very important to pick where you want the tank FBX files written.
Side note. The paths are absolute in my FBX writer.
You can convert all of them at once to a later version using Autodesks FBX converter.
That should also make the paths relative to the FBX's location and not absolute.
If you can not get the paths to the textures as relative, you could always create the same paths you would have on the server locally and that path to write all the FBX to. It would make sense anyway if you have a test server setup at home.
There is a link to it on the main code page at the top of the README.
http://tnmshouse.com/public
You will find the 110 version installer at the above location.
Once again.. BE CAREFUL WHERE YOU POINT THIS DUMP TO!
**You can abort by pressing ESCAPE at any time.**

**Comment by mikeoverbay** [comment]
Oh.. and if you have any issues.. let me know.. Also.. feel free to throw a few bucks my way. Not many are willing to do this sort a thing just for kicks ;) DONATE BUTTON TOP RIGHT!

**Comment by mikeoverbay** [comment]
I believe there is a FBX reader out there for webGL. FBX isn't the easiest thing to understand and examples are far and few between. If you get hung up, I can probably help.

**Comment by mikeoverbay** [comment]
All textures are exported including the GMM maps so.. if you want to attempt PBS shading, it is an option. There are 2 shaders in Tank Exporter that do PBS.. the better one is the primitives shader. It is cleaner and probably easier to follow. You will need a cube map environment to get the best results. It affects the finally color of the model. You do NOT have to have it to get realistic materials.

**Comment by mikeoverbay** [comment]
I forgot.. Some tanks default gun_01 is not the top gun. The M-46 Patton is one of those tanks. There are others but I don't remember them all.. Just export the FBX for the ones that are screwy but load the right gun.

**Comment by amelkikh** [comment]
This task can be closed, thanks for the help

**Comment by mikeoverbay** [comment]
You're welcome
