### ISSUE TITLE
Option to proceed without decals folder

### ISSUE THREAD

**Issue by red1134** [mikeoverbay/TankExporter#32]
I hate waiting for it to rebuild everything whenever this damned folder goes missing (literally not using TE for 3 days and it goes missing). I just extract the models for 3D renders and making cool looking scenes. I don't need the contents of the decal folder, whatever it even is. Waiting SUCKS, please give option to just ignore the missing folder.

**Comment by mikeoverbay** [comment]
The reason that folder gets removed is either windows storage sense BS or some other app like CCleaner.
In CCleaner, you can add exemptions. This can NOT be done in windows. They are not smart enough to add that option.
You can stop windows from doing this and use an app like CCleaner.
https://winaero.com/disable-storage-sense-delete-temporary-files-windows-10/#:~:text=Go%20to%20Computer%20Configuration%5CAdministrative,always%20disabled%20for%20all%20users.

**Comment by red1134** [comment]
This still doesn't answer my request directly to add an option on startup to proceed _**WITHOUT**_ the decal folder seeing as I have no need for it.

**Comment by mikeoverbay** [comment]
I am sorry for not getting back. I've been very sick with lung infections.

The decals folder is use to store the decals used on the terrain.
In order to disable the loading of decals will take a bit of effort.
It will require:
Disabling loading and saving them from the PKG files.
Disabling the rendering of the terrain.
Disable the tool to edit the terrain decals.
Modifying the background display mode button. (terrain, grid, none)
Adding a mechanism to disable/modify the above and save that preference at startup.
It will take some time... 
I'll let you know when this is added.
Feel free to donate for all the work I have done on this app for the last 4 years.

**Comment by mikeoverbay** [comment]
I added the changes.
A box will show up before the terrain is loaded.. Just check it and close that box.
Did some other things too.. Check out the README.
