### ISSUE TITLE
Tank exporter crash

### ISSUE THREAD

**Issue by jaguar42l** [mikeoverbay/TankExporter#36]
Hello,

I've got this error when executing tank exporter:
![image](https://user-images.githubusercontent.com/83211809/116056622-4c3ba700-a67e-11eb-98dc-9d1fe1c3c202.png)

Best regards

**Comment by mikeoverbay** [comment]
I can't read the language but.. I can see that it is crashing reading a zip from one of the packages.
I have not seen this issue unless a PKG file is corrupt.
It found the pkg and is trying to read it. WOT pkgs have no compression. The are store only zips.
I would run their app to check the game or uninstall it, and reinstall.
Because of where it has crashed, It is looking for the thump nail images of the tanks. Those are located in the gui_part1 and gui_part2 pkg files.
If reinstalling the game or running their check program doesn't fix it, let me know.

**Comment by PeNeTrAtOrX** [comment]
![translated](https://user-images.githubusercontent.com/29421174/116800830-cf3c8180-ab04-11eb-9cf2-0ea1406ec2fe.jpg)

**Comment by jaguar42l** [comment]
Hello,

I launched WOT check program and it found that vehicules level 3 package was corrupted.
After downloading it, Tank Exporter is now working fine.

Thank you very much
