### ISSUE TITLE
Dump upgrades with tanks

### ISSUE THREAD

**Issue by Official-Husko** [mikeoverbay/TankExporter#39]
Would it be possible to export the upgrades too with the tanks? possibly just combined with the tank in one file. With the option to dump all tanks with their available upgrades inside one fbx file. Would be nice to have such a feature.

**Comment by mikeoverbay** [comment]
Sounds like adding code to load all available parts for the tank.
Let me think about this and the work involved.
I already create a list of all parts and select the one with the highest _N number as in gun_04 or gun_05.
I'd need to add code to loop through all the lists, load each part and added it to the tank regardless of if a part like a gun is already loaded.
Because the transforms are specific to each part number and its design, this could cause problems.
Some guns will or will not work with the different turrets.
I don't this I can do this with out rewriting how the matrix stack is created and even then.. I'm not sure it would work.

**Comment by Official-Husko** [comment]
Its no problem if its not really possible. Its an idea and it would be nice if it was possible.

**Comment by mikeoverbay** [comment]
Yes.. I just don't think it's possible with the matrix stack issue.
I'm going to close this..
Great idea though :)
