### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Proigr3** [mikeoverbay/TankExporter#41]
I just downloaded TankExporter, installed it, and this happened. Is there a fix?
Firstly, it asks me to change the root directory of WoT, so I do
"Y:/*/World_of_Tanks_EU/"
![SharedScreenshot](https://user-images.githubusercontent.com/35418130/129458821-fc09f266-8cd0-492c-a6d7-9ce45c975f25.jpg)
then it says to update the "decals folder" so I click yes, if I dont the app closes.
![SharedScreenshot01](https://user-images.githubusercontent.com/35418130/129458822-e97475da-0382-40ab-bcb3-bdd1f7991362.jpg)
And it crashes with this message, I can click on continue and it keeps "running" but nothing happens.
![SharedScreenshot02](https://user-images.githubusercontent.com/35418130/129458824-da0bc5fb-6d2e-40f8-8b7b-d066739c5b8c.jpg)
How to solve this? Thanks.

**Comment by mikeoverbay** [comment]
First. Sorry for not getting back sooner. I've been very busy
Second.. I have never seen this before.
The apps data is stored in users/username/AppData/Local/temp/wot_temp
It seems that Tank Exporter cant find the decals folder in that path.
This might happen if when the first time you ran Tank Exporter, you told it not to use decals for the terrain.
It should not error because of this but I can think of any reason that the missing message would show up.
Look for that path and see if the decals folder is indeed missing.
You will have to make AppData accessible. Look online as to how to do this.

Try uninstalling Tank Exporter and then... go to
users/username/AppData/Local/Coffee_ and delete every folder that has !_Tank_Exporter.exe_ in its name. There should only be one. If there are more.. delete them also. This happens when there is an update install.
After reinstall Tank Exporter and make sure you do NOT block decals from loading!

Let me know :)
Sorry you are having problems. I'll do my best to help you get it running.

**Comment by Proigr3** [comment]
Thank you for help! Deleteing "C:\Users\%username%\AppData\Local\Coffee_" and "C:\Users\%username%\AppData\Local\Temp\wot_temp" solved the issue. I think the problem was, that I was trying to load World of Tanks version 0.8.9, yes I still have a copy of it, instead of version 1.14

**Comment by mikeoverbay** [comment]
Oh that is good news!
A simple fix :)
If there are any other problems, let me know.
