### ISSUE TITLE
Textures break models

### ISSUE THREAD

**Issue by Luna-wolf** [mikeoverbay/TankExporter#49]
Tanks are all spikes with textures enabled, unsure if it's a corruption, something with the game, or my own error, but it's weird

**Comment by mikeoverbay** [comment]
What video card. It's probably a shader that wont run on the hardware.

Try "Simple Lighting"
File/Settings -> UI and View Settings -> Simple Lighting
This bypasses the shaders and uses direct mode. If your hardware wont support direct mode, you are probably screwed. AMD has never fixed its OpenGL issues because they love Bill Gates.

**Comment by Luna-wolf** [comment]
I apologize, I forgot I had posted this one!

I'm using a Radeon RX 6700 XT 12g. I will try simple lighting!

Also as for my FBX concern, I read the FBX converter thing a little late haha

**Comment by mikeoverbay** [comment]
The wrapper for FBX I'm using is old and only supports 2009 FBX.

I was hoping to get my hands on a Radeon for testing but I have little money on my fixed income.

**Comment by Luna-wolf** [comment]
If you need a tester with a radeon GPU, I am more than willing to help out! Just let me know, I have so much spare time that it is hard to find stuff to do haha

Also a screenshot is attatched with simple lighting enabled. The textures look slightly odd
![image](https://user-images.githubusercontent.com/47584772/155593577-8766851f-5be0-4b2a-a9e9-2b120e8d3937.png)

**Comment by mikeoverbay** [comment]
Thanks for the offer. I'll keep that in mind.
I need someone that understands AMD GLSL glitches and I can't find anyone.
