### ISSUE TITLE
TE compatibility? 

### ISSUE THREAD

**Issue by Lyroi** [mikeoverbay/TankExporter#78]
So I've revisited TE again in a while, but now I cant even load the tank models anymore. Is it optimized onto RTX architecture? Because in that period I went from Nvidia to Radeon

**Comment by mikeoverbay** [comment]
AMD has had known bugs in its OpenGL since I can remember.
They don't seam to interested in fixing it as its a forever thing they chose to ignore.
I am sorry but yeah..  It won't work.
If you can get to the main window with out it crashing, go to file--> graphic settings --> check Simple Shading. It might help.

**Comment by Lyroi** [comment]
![image](https://user-images.githubusercontent.com/118940676/228664550-13bc11cf-dea6-44fb-b4c6-9e144edc1147.png)
Is it this setting? Little different but same corner

**Comment by Lyroi** [comment]
Another problem. So I fixed the crashing since I have a laptop with an Nvidia card, but it isnt loading the textures. There's just a black blob in the middle of my screen.

**Comment by mikeoverbay** [comment]
can put post an image of what it looks like?

**Comment by mikeoverbay** [comment]
I did a lot of work on this lastnight. Try updating to version 129
https://github.com/mikeoverbay/TankExporter/blob/master/TankExporter_129.msi

**Comment by mikeoverbay** [comment]
this should be fixed.

**Comment by Lyroi** [comment]
Yeah it's fixed, been a year after all, new pc, new gpu, new everything :)
