### ISSUE TITLE
Crashing when loading models

### ISSUE THREAD

**Issue by 1stSavagerY** [mikeoverbay/TankExporter#89]
Thank you for helping me with my last issue, but a new one has arisen.  When loading models from the right side, the program crashes without loading the model. I have made sure that the file paths are set correctly and I have cleared the temp folder, as well as doing fiddling with some of the settings.  I have also tried versions 127, 130, 135, and 138 and all have crashed when I try to load the model.

**Comment by Stromy08** [comment]
the same thing was happening to me before aswell and i fully reset my pc and drivers and it still is broken, i dont know if its because im using amd integrated cpu graphics

**Comment by mikeoverbay** [comment]
I will look in to this.
All models or just some?

**Comment by mikeoverbay** [comment]
Can you post what errors are thrown if any?

**Comment by 1stSavagerY** [comment]
> I will look in to this. All models or just some?

It occurs with any model, and I am also unable to import any FBX models to view either.  I get no errors, the program just says "Working" on the top right then shuts down.

**Comment by NatetheGreaterest** [comment]
I am having the same problem. I tried using the "export all tanks to fbx" button but the 3d models and texture files were empty.

**Comment by mikeoverbay** [comment]
oh my.. OK guys. I will do my best to get this fixed . I will need to find what is causing the root issue but if I can't duplicate the crash, It's going to be a MOFO to find it.

I'll update after some testing.

**Comment by NatetheGreaterest** [comment]
I cant find the wottemp file. I can send a recording of the program crashing if you want.

**Comment by 1stSavagerY** [comment]
I started up TE and followed your instructions but unfortunately no files named Startup_log.txt popped up in that folder

**Comment by mikeoverbay** [comment]
Ok.. 
Let me make some changes.

**Comment by mikeoverbay** [comment]
OK...
This is where the log_text.txt is.. I changed the name.
C:\Users\YOURUSERNAME\AppData\Local\Temp\wot_temp\log_text.txt
Download and run the Tank_Exporter_BUGs.msi.
After it crashes, find that file and go to the bottom.
I need to know how far we got when trying to load the tank..
Thanks for the understanding and help!
https://github.com/mikeoverbay/TankExporter/blob/master/Tank_Exporter_BUGs.msi

**Comment by NatetheGreaterest** [comment]
This is what I found in the log_text:

----- Startup Complete -----
 ======== Model Load Start =========

File name = C:\Games\World_of_Tanks_NA/res/packages/vehicles_level_01-part3.pkg:vehicles/british/GB03_Cruiser_Mk_I

XML path = vehicles\british\GB03_Cruiser_Mk_I.xml

Got XML data for tank

Path of component = vehicles\british\GB03_Cruiser_Mk_I\normal\lod0\Gun_01.model

Path of component = vehicles\british\GB03_Cruiser_Mk_I\normal\lod0\Gun_02.model

Path of component = vehicles\british\GB03_Cruiser_Mk_I\normal\lod0\Turret_01.model

Path of component = vehicles\british\GB03_Cruiser_Mk_I\normal\lod0\Hull.model

Path of component = vehicles\british\GB03_Cruiser_Mk_I\normal\lod0\Chassis.model

After frmComponents.ShowDialog

**Comment by mikeoverbay** [comment]
OK.. This helps narrow it down.
I am adding more traps to drill down deeper in the loading.
I added more bug output.
Please install the BUGs and let me know..
Thanks!

**Comment by 1stSavagerY** [comment]
im getting the exact same text with the window closing as well

**Comment by mikeoverbay** [comment]
OK.. Let me do some hunting

**Comment by mikeoverbay** [comment]
OK.. do it again. Install BUGs and let me know what the log says.

**Comment by NatetheGreaterest** [comment]
Btw, up to this point, I have only been copying the tank load up part of the log and not the startup, just thought I would say that.

----- Startup Complete -----
 ======== Model Load Start =========

File name = C:\Games\World_of_Tanks_NA/res/packages/vehicles_level_01-part3.pkg:vehicles/sweden/S05_Strv_M21_29

XML path = vehicles\sweden\S05_Strv_M21_29.xml

Got XML data for tank

Path of component = vehicles\sweden\S05_Strv_M21_29\normal\lod0\Gun_01.model

Path of component = vehicles\sweden\S05_Strv_M21_29\normal\lod0\Gun_02.model

Path of component = vehicles\sweden\S05_Strv_M21_29\normal\lod0\Turret_01.model

Path of component = vehicles\sweden\S05_Strv_M21_29\normal\lod0\Hull.model

Path of component = vehicles\sweden\S05_Strv_M21_29\normal\lod0\Chassis.model

After frmComponents.ShowDialog

started_loading_primitive
tank component name: vehicles/sweden/S05_Strv_M21_29/normal/lod0/Chassis.primitives_processed
got ordered names
Buf filled
Section table read
.indi_name using table index 3
.vert_name using table index 3
.uv2_name using table index 3
.indi_name using table index 2
.vert_name using table index 2
.uv2_name using table index 2
.indi_name using table index 1
.vert_name using table index 1
.indi_name using table index 0
.vert_name using table index 0
 
List indi size 2
location data
startIndex_ 0
nPrimitives_ 4054
startVertex_ 0
nVertices_ 4542

vh_header BPVTxyznuviiiwwtb
read geo data
Display list created 1

Once again the window crashes

**Comment by NatetheGreaterest** [comment]
Weird, im not sure if the result was supposed to be the same, but the download for the bug version I downloaded as from 5 hours when we tested earlier, so did I just test an old version of the bug tester?

**Comment by mikeoverbay** [comment]
What I changed was when it draws the the tank parts. Before, It would draw each part and load the next.
I did this to see if it was a rendering issue but, it does not look like this is the issue.
The bug is somewhere else but it is being narrowed down.

This is the code in that section.
  ```
                make_lists(jj)
                frmMain.update_log("Display list created " + jj.ToString)
                _object(jj).find_center() 'must be after pre transform!

                _object(jj).modified = False
                GC.Collect()
                _group(jj).table_entry_name = ordered_names(sg - sub_groups).indi_name

                frmMain.update_log("object created " + jj.ToString)

            Next jj
```
Each loop should write info to the log_text each time it loads a part of the chassis. It is not and is crashing before it does.
Let me add some more writes to the log_text.
I'll add a write between each statement and will see where it crashes.
It never makes it to the "object created" so it has to be in one of these function calls.

**Comment by mikeoverbay** [comment]
Try it again..
Sorry :(

**Comment by NatetheGreaterest** [comment]
The bugtest.msi download is the same as it was before, but the file at the top of the download page is different, what do I do to update it?

**Comment by mikeoverbay** [comment]
uninstall and install the msi.
I am not changing versions until we get this fixed, OK?

**Comment by NatetheGreaterest** [comment]
Log shows this: 

----- Startup Complete -----
 ======== Model Load Start =========

File name = C:\Games\World_of_Tanks_NA/res/packages/vehicles_level_01-part3.pkg:vehicles/poland/Pl14_4TP

XML path = vehicles\poland\Pl14_4TP.xml

Got XML data for tank

Path of component = vehicles\poland\Pl14_4TP\normal\lod0\Gun_01.model

Path of component = vehicles\poland\Pl14_4TP\normal\lod0\Gun_02.model

Path of component = vehicles\poland\Pl14_4TP\normal\lod0\Turret_01.model

Path of component = vehicles\poland\Pl14_4TP\normal\lod0\Hull.model

Path of component = vehicles\poland\Pl14_4TP\normal\lod0\Chassis.model

After frmComponents.ShowDialog

started_loading_primitive
tank component name: vehicles/poland/Pl14_4TP/normal/lod0/Chassis.primitives_processed
got ordered names
Buf filled
Section table read
.indi_name using table index 3
.vert_name using table index 3
.uv2_name using table index 3
.indi_name using table index 2
.vert_name using table index 2
.uv2_name using table index 2
.indi_name using table index 1
.vert_name using table index 1
.indi_name using table index 0
.vert_name using table index 0
 
List indi size 2
location data
startIndex_ 0
nPrimitives_ 4634
startVertex_ 0
nVertices_ 5071

vh_header BPVTxyznuviiiwwtb
read geo data
Display list created 1

The window then closes

**Comment by CZECHPWMODS** [comment]
Ok, I tried Uninstall Tank Exporter, delete WOT temp folder, then again install Tank Exporter, I set paths and load tank...and it crashed.

**Comment by mikeoverbay** [comment]
is the terrain rendering OK?

> Ok, I tried Uninstall Tank Exporter, delete WOT temp folder, then again install Tank Exporter, I set paths and load tank...and it crashed.
Did you find the log_text.txt file? If so, can you post what the last line is in it?

**Comment by mikeoverbay** [comment]
This is the one you installed?
https://github.com/mikeoverbay/TankExporter/blob/master/Tank_Exporter_BUGs.msi

**Comment by CZECHPWMODS** [comment]
> 

Yes
I tried it with both versions. Always ends same

**Comment by 1stSavagerY** [comment]
> I am trying. What video board/chip are you using. Model and memory?

I have an AMD Ryzen 7 3700 3.6 GHz 8-core processor
MSI Radeon TX 5700 XT 8 GB Mech OC Video Card

**Comment by CZECHPWMODS** [comment]
> is the terrain rendering OK?
> 
> > Ok, I tried Uninstall Tank Exporter, delete WOT temp folder, then again install Tank Exporter, I set paths and load tank...and it crashed.
> > Did you find the log_text.txt file? If so, can you post what the last line is in it?

Yes terrain is fine

**Comment by CZECHPWMODS** [comment]
> > I am trying. What video board/chip are you using. Model and memory?
> 
> I have an AMD Ryzen 7 3700 3.6 GHz 8-core processor MSI Radeon TX 5700 XT 8 GB Mech OC Video Card

I have and AMD Athlon silver 3050 with Radeon Graphics

**Comment by NatetheGreaterest** [comment]
I also have an rx 570 gpu, with an ryzen 5 5500. I just bought a new laptop, ill try tank exporter on there and see if it works.

**Comment by mikeoverbay** [comment]
Well.. If it displays the terrain, it supports display lists.
So.. It has to be something with the way the display list is created for the tank models as its crashing immediately after.
Tomorrow, I'll look at this and we'll try a few things. 
Hang in there :)

**Comment by mikeoverbay** [comment]
Sorry guys..
I got out my crap AMD AIO computer and tried bugs on it.
I loads everything but it is throwing a 1281 gl error. In valid value.
I am investigating.

**Comment by NatetheGreaterest** [comment]
Btw, upon exporting, everything is normal. Now all I have to do is figure out how to add objects to the vehicle and how to add textures to them.

**Comment by CZECHPWMODS** [comment]
> Btw, upon exporting, everything is normal. Now all I have to do is figure out how to add objects to the vehicle and how to add textures to them.

Where did you get it?

**Comment by NatetheGreaterest** [comment]
@CZECHPWMODS Click on the COMMITS button above the download section and scroll down to 1.0.0.135 and download it.

**Comment by mikeoverbay** [comment]
Oh.. This one might work better.
https://github.com/mikeoverbay/TankExporter/blob/master/Tank_Exporter_BUGs.msi

I stop writing with mulitexCoords. It throws an error on my AMD chip.
However, I an not using Tangent and Bitangent for rendering so it's not going to be as pretty but it should be more than enough to work in.

**Comment by 1stSavagerY** [comment]
i no longer crash with that latest BUGs version.  i am able to load models but not terrain.  however i dont know if this is a once off so if it doesnt work again i will let you know

**Comment by mikeoverbay** [comment]
Thank you for testing.. It can get frustrating. lol
Can you test the T-57 usa tier 10? It loads for me but others are having issues.

Also.. I will continue to work on this until I find a way to get the tangent and bitangent in to the shader that AMD cards will work with.

**Comment by mikeoverbay** [comment]
Can you try version 139 and let me know it it works for you?
I finally found out what was wrong.
This is correct and how it should be,
Gl.glMultiTexCoord2f(Gl.GL_TEXTURE0
This is incorrect and how I had coded it.
Gl.glMultiTexCoord2f(0
Odd Nvidia works at all. It should throw an error but does not.

**Comment by devidbyte0** [comment]
I am getting this Error when I try to even LOAD the modules ( number 05 ) 

 https://gyazo.com/e1d6c1df6d9893840b2b0561bb2e8a16

and the follow is in the error log 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Tank_Exporter.frmMain.store_in_treeview(Int32 i, TreeView& tn)
   at Tank_Exporter.frmMain.load_tabs()
   at Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9186.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
!_Tank Exporter
    Assembly Version: 1.0.0.139
    Win32 Version: 1.0.0.139
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/!_Tank%20Exporter.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9176.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9186.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/SharpDX.Mathematics.DLL
----------------------------------------
Ionic.Zip
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Ionic.Zip.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FbxSDK
    Assembly Version: 1.0.4593.24947
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/FbxSDK.DLL
----------------------------------------
cttools
    Assembly Version: 1.0.4723.22902
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/cttools.DLL
----------------------------------------
msvcm90
    Assembly Version: 9.0.30729.9625
    Win32 Version: 9.00.30729.9625
    CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9625_none_508ef7e4bcbbe589/msvcm90.dll
----------------------------------------
Tao.DevIl
    Assembly Version: 1.6.8.3
    Win32 Version: 1.6.8.3
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.DevIl.DLL
----------------------------------------
Tao.OpenGl
    Assembly Version: 2.1.0.12
    Win32 Version: 2.1.0.12
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.OpenGl.DLL
----------------------------------------
Tao.Platform.Windows
    Assembly Version: 1.0.0.5
    Win32 Version: 1.0.0.5
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.Platform.Windows.DLL
----------------------------------------
Tao.FreeGlut
    Assembly Version: 2.4.0.2
    Win32 Version: 2.4.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.FreeGlut.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by mikeoverbay** [comment]
I dont know where this is so im closing it.
