### ISSUE TITLE
Exported fole cant be opened in Blender

### ISSUE THREAD

**Issue by Arkhorse** [mikeoverbay/TankExporter#9]
Hi, blender now uses 7100 or newer, please update! Thanks for all your work :)

**Comment by mikeoverbay** [comment]
Hello...
Tank Exporter uses a wrapper to add the FBX export/import functions. This wrapper had not been updated since it was released. To rewrite Tank Exporter to work with a different wrapper is an intensive amount of work.
The best thing to do and easiest is to convert the file to a newer version using Autodesk's FBX converter.
You can find it here: https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives
Make sure yo select the version for your OS.. 32 or 64 bit.
