### ISSUE TITLE
How do can i load tanks from special gamemodes?

### ISSUE THREAD

**Issue by MatMal007** [mikeoverbay/TankExporter#97]

**Comment by xurco** [comment]
Can anyone tell me what level the tanks from Steel Hunter are?

**Comment by Stromy08** [comment]
Idk if that might help u but fastest classic recommended me a blender plugin to import tanks, I'll try and find it later just reply to this pls cuz I'll probably forget. But it is ables to import custom tanks

**Comment by Fotoradar606** [comment]
> Can anyone tell me what level the tanks from Steel Hunter are?

They are on tier 1, but I can't seem to be able to load the models themselves

Tho I was able to force load the Walkure, by reskining the tank(only turret and gun work) it's based off(put it's file in the res_mods/[version]/vechicles/[country]/ and remove the _sh). 

The problem is, after I added parts of the tank to another and loaded the fbx back into tank explorer, it crashes when trying to write primitives   :(
